-- CONSULTAR
CREATE OR ALTER PROCEDURE ConsultarMovimientos
    @FechaInicio VARCHAR(50) = NULL,
    @FechaFin VARCHAR(50) = NULL,
    @TipoMovimiento VARCHAR(50) = NULL,
    @NroDocumento VARCHAR(50) = NULL
AS
BEGIN
    SELECT *
    FROM MOV_INVENTARIO
    WHERE (@FechaInicio IS NULL OR FECHA_TRANSACCION >= @FechaInicio)
    AND (@FechaFin IS NULL OR FECHA_TRANSACCION <= @FechaFin)
    AND (@TipoMovimiento IS NULL OR TIPO_MOVIMIENTO = @TipoMovimiento)
    AND (@NroDocumento IS NULL OR NRO_DOCUMENTO = @NroDocumento)
END
GO

-- ACTUALIZAR
CREATE OR ALTER PROCEDURE ActualizarMovimiento
    @COD_CIA VARCHAR(50),
    @COMPANIA_VENTA_3 VARCHAR(50),
    @ALMACEN_VENTA VARCHAR(50),
    @TIPO_MOVIMIENTO VARCHAR(50),
    @TIPO_DOCUMENTO VARCHAR(50),
    @NRO_DOCUMENTO VARCHAR(50),
    @COD_ITEM_2 VARCHAR(50),
    @PROVEEDOR VARCHAR(50),
    @N_PARM_SAL INT OUTPUT,
    @C_PARM_SAL VARCHAR(250) OUTPUT
AS
BEGIN
    BEGIN TRY
        UPDATE MOV_INVENTARIO
        SET PROVEEDOR = @PROVEEDOR
        WHERE COD_CIA = @COD_CIA
            AND COMPANIA_VENTA_3 = @COMPANIA_VENTA_3
            AND ALMACEN_VENTA = @ALMACEN_VENTA
            AND TIPO_MOVIMIENTO = @TIPO_MOVIMIENTO
            AND TIPO_DOCUMENTO = @TIPO_DOCUMENTO
            AND NRO_DOCUMENTO = @NRO_DOCUMENTO
            AND COD_ITEM_2 = @COD_ITEM_2
        
        SET @N_PARM_SAL = 0
        SET @C_PARM_SAL = 'Éxito: Registro actualizado correctamente'
    END TRY
    BEGIN CATCH
        SET @N_PARM_SAL = 1
        SET @C_PARM_SAL = 'Error: ' + ERROR_MESSAGE()
    END CATCH
END
GO

-- INSERTAR
CREATE OR ALTER PROCEDURE InsertarMovimiento
    @COD_CIA VARCHAR(50),
    @COMPANIA_VENTA_3 VARCHAR(50),
    @ALMACEN_VENTA VARCHAR(50),
    @TIPO_MOVIMIENTO VARCHAR(50),
    @TIPO_DOCUMENTO VARCHAR(50),
    @NRO_DOCUMENTO VARCHAR(50),
    @COD_ITEM_2 VARCHAR(50),
    @PROVEEDOR VARCHAR(50),
    @ALMACEN_DESTINO VARCHAR(50) = NULL,
    @CANTIDAD VARCHAR(50) = NULL,
    @COMPANIA_DESTINO VARCHAR(50) = NULL,
    @COSTO_UNITARIO VARCHAR(50) = NULL,
    @DOC_REF_1 VARCHAR(50) = NULL,
    @DOC_REF_2 VARCHAR(50) = NULL,
    @FECHA_TRANSACCION VARCHAR(50) = NULL,
    @MOTIVO VARCHAR(50) = NULL,
    @PRECIO_UNITARIO VARCHAR(50) = NULL,
    @TIPO_DOC_REF VARCHAR(50) = NULL,
    @UM_ITEM_3 VARCHAR(50) = NULL,
    @NRO_NOTA VARCHAR(50) = NULL,
    @ROWVERSION VARCHAR(50) = NULL,
    @USUARIO VARCHAR(50) = NULL,
    @MONEDA VARCHAR(50) = NULL,
    @COSTO_UNITARIO_ME VARCHAR(50) = NULL,
    @COS_UNIT_EST VARCHAR(50) = NULL,
    @COS_UNIT_ME_EST VARCHAR(50) = NULL,
    @HORA_TRANSACCION VARCHAR(50) = NULL,
    @F_ORDENCOMPRA VARCHAR(50) = NULL,
    @C_SEC_OC VARCHAR(50) = NULL,
    @C_SEC_DET_OC VARCHAR(50) = NULL,
    @TIPO_DOC_REF_2 VARCHAR(50) = NULL,
    @OBSERVACION VARCHAR(50) = NULL,
    @FECHA_VALORIZACION VARCHAR(50) = NULL,
    @USUARIO_VALORIZA VARCHAR(50) = NULL,
    @FACTOR VARCHAR(50) = NULL,
    @COSTOS_ADICIONALES VARCHAR(50) = NULL,
    @T_CAMBIO_VALORIZA VARCHAR(50) = NULL,
    @PERIODO_CERRADO VARCHAR(50) = NULL,
    @PLANILLA_CONSIGNA VARCHAR(50) = NULL,
    @DOC_REF_3 VARCHAR(50) = NULL,
    @INGRESO_SALIDA VARCHAR(50) = NULL,
    @SALDO_FINAL VARCHAR(50) = NULL,
    @FLAG_URGENTE VARCHAR(50) = NULL,
    @DOC_REF_4 VARCHAR(50) = NULL,
    @DOC_REF_5 VARCHAR(50) = NULL,
    @DOC_REF_6 VARCHAR(50) = NULL,
    @DOC_REF_7 VARCHAR(50) = NULL,
    @DOC_REF_8 VARCHAR(50) = NULL,
    @N_PARM_SAL INT OUTPUT,
    @C_PARM_SAL VARCHAR(250) OUTPUT
AS
BEGIN
    BEGIN TRY
        INSERT INTO MOV_INVENTARIO (
            COD_CIA, COMPANIA_VENTA_3, ALMACEN_VENTA, 
            TIPO_MOVIMIENTO, TIPO_DOCUMENTO, NRO_DOCUMENTO, 
            COD_ITEM_2, PROVEEDOR, ALMACEN_DESTINO, 
            CANTIDAD, COMPANIA_DESTINO, COSTO_UNITARIO, 
            DOC_REF_1, DOC_REF_2, FECHA_TRANSACCION, 
            MOTIVO, PRECIO_UNITARIO, TIPO_DOC_REF, 
            UM_ITEM_3, NRO_NOTA, ROWVERSION, 
            USUARIO, MONEDA, COSTO_UNITARIO_ME, 
            COS_UNIT_EST, COS_UNIT_ME_EST, HORA_TRANSACCION, 
            F_ORDENCOMPRA, C_SEC_OC, C_SEC_DET_OC, 
            TIPO_DOC_REF_2, OBSERVACION, FECHA_VALORIZACION, 
            USUARIO_VALORIZA, FACTOR, COSTOS_ADICIONALES, 
            T_CAMBIO_VALORIZA, PERIODO_CERRADO, PLANILLA_CONSIGNA, 
            DOC_REF_3, INGRESO_SALIDA, SALDO_FINAL, 
            FLAG_URGENTE, DOC_REF_4, DOC_REF_5, 
            DOC_REF_6, DOC_REF_7, DOC_REF_8
        ) VALUES (
            @COD_CIA, @COMPANIA_VENTA_3, @ALMACEN_VENTA, 
            @TIPO_MOVIMIENTO, @TIPO_DOCUMENTO, @NRO_DOCUMENTO, 
            @COD_ITEM_2, @PROVEEDOR, @ALMACEN_DESTINO, 
            @CANTIDAD, @COMPANIA_DESTINO, @COSTO_UNITARIO, 
            @DOC_REF_1, @DOC_REF_2, @FECHA_TRANSACCION, 
            @MOTIVO, @PRECIO_UNITARIO, @TIPO_DOC_REF, 
            @UM_ITEM_3, @NRO_NOTA, @ROWVERSION, 
            @USUARIO, @MONEDA, @COSTO_UNITARIO_ME, 
            @COS_UNIT_EST, @COS_UNIT_ME_EST, @HORA_TRANSACCION, 
            @F_ORDENCOMPRA, @C_SEC_OC, @C_SEC_DET_OC, 
            @TIPO_DOC_REF_2, @OBSERVACION, @FECHA_VALORIZACION, 
            @USUARIO_VALORIZA, @FACTOR, @COSTOS_ADICIONALES, 
            @T_CAMBIO_VALORIZA, @PERIODO_CERRADO, @PLANILLA_CONSIGNA, 
            @DOC_REF_3, @INGRESO_SALIDA, @SALDO_FINAL, 
            @FLAG_URGENTE, @DOC_REF_4, @DOC_REF_5, 
            @DOC_REF_6, @DOC_REF_7, @DOC_REF_8
        )
        
        SET @N_PARM_SAL = 0
        SET @C_PARM_SAL = 'Éxito: Registro insertado correctamente'
    END TRY
    BEGIN CATCH

        SET @N_PARM_SAL = 1
        SET @C_PARM_SAL = 'Error: ' + ERROR_MESSAGE()
    END CATCH
END
GO

-- BUSCARPORID
CREATE OR ALTER PROCEDURE BuscarMovimientoPorID
    @COD_CIA VARCHAR(50),
    @COMPANIA_VENTA_3 VARCHAR(50),
    @ALMACEN_VENTA VARCHAR(50),
    @TIPO_MOVIMIENTO VARCHAR(50),
    @TIPO_DOCUMENTO VARCHAR(50),
    @NRO_DOCUMENTO VARCHAR(50),
    @COD_ITEM_2 VARCHAR(50),
    @N_PARM_SAL INT OUTPUT,
    @C_PARM_SAL VARCHAR(250) OUTPUT
AS
BEGIN
    BEGIN TRY
        SELECT *
        FROM MOV_INVENTARIO
        WHERE COD_CIA = @COD_CIA
            AND COMPANIA_VENTA_3 = @COMPANIA_VENTA_3
            AND ALMACEN_VENTA = @ALMACEN_VENTA
            AND TIPO_MOVIMIENTO = @TIPO_MOVIMIENTO
            AND TIPO_DOCUMENTO = @TIPO_DOCUMENTO
            AND NRO_DOCUMENTO = @NRO_DOCUMENTO
            AND COD_ITEM_2 = @COD_ITEM_2

        SET @N_PARM_SAL = 0
        SET @C_PARM_SAL = 'Éxito: Búsqueda realizada correctamente'
    END TRY
    BEGIN CATCH

        SET @N_PARM_SAL = 1
        SET @C_PARM_SAL = 'Error: ' + ERROR_MESSAGE()
    END CATCH
END
